---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.1/rolebinding-rbac-v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: &name "${NAMESPACE}-secrets"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: *name
subjects:
  - kind: ServiceAccount
    name: *name
    namespace: "${NAMESPACE}"
