---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ${SECRET_DOMAIN/./-}-tls
spec:
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: akeyless-secret-store
  selector:
    secret:
      name: "${SECRET_DOMAIN/./-}-production-tls"
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "${VAULT_PREFIX}/production-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "${VAULT_PREFIX}/production-tls"
          property: *key
