---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name crunchy-postgres
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .S3_KEY_ID  }}
          repo1-s3-key-secret={{ .S3_SECRET_KEY  }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .POSTGRES_BACKUP_CIPHER_PASS }}
  dataFrom:
    - extract:
        key: korg/postgres
    - extract:
        key: korg/qnap
