---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
components:
  - ../../clusters/kdev
  - ../../components/common
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ../../common/cert-manager/cert-manager.yaml
