#file: noinspection YAMLSchemaValidation
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${APP}-volsync"
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      data:
        RESTIC_REPOSITORY: "s3:{{ .QNAP_URL }}:8010/${VOLSYNC_S3_BUCKET}/${APP}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .S3_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: korg/volsync
    - extract:
        key: korg/qnap
