---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linstor-gui
  annotations:
    external-dns.alpha.kubernetes.io/target: "linstor.${SECRET_DOMAIN}"
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "piraeus-datastore/linstor-gui-tls"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/secure-backends: "true"
  labels:
    app.kubernetes.io/instance: linstor-gui
    app.kubernetes.io/name: linstor-gui
spec:
  ingressClassName: internal
  rules:
  - host: "linstor.${SECRET_DOMAIN}"
    http:
      paths:
      - backend:
          service:
            name: linstor-controller
            port:
              number: 3371
        path: /
        pathType: Prefix
