---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: wolf
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/brunnels/fenrir/helm-chart/charts/wolf
