---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wolf
spec:
  chart:
    spec:
      chart: ./charts/wolf
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: *app
  interval: 1h
  values: []
