---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
#  - ./alertmanager-silencer/ks.yaml
  - ./exporters
#  - ./gatus/ks.yaml
#  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
#  - ./peanut/ks.yaml
#  - ./promtail/ks.yaml
#  - ./runbook-viewer/ks.yaml
