---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${NAMESPACE}-pgadmin
  annotations:
    gethomepage.dev/description: Postgres Database Manager
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Management
    gethomepage.dev/icon: si-postgresql
    gethomepage.dev/name: pgAdmin
spec:
  hostnames: ["${NAMESPACE}-pgadmin.${SECRET_DOMAIN}"]
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: "${NAMESPACE}-pgadmin"
          port: 5050
