---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.1/serviceaccount-v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "${NAMESPACE}-secrets"
