---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name vpn-gateway
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        PUBLICIP_API: ip2location
        PUBLICIP_API_TOKEN: "{{ .IP2LOCATION_TOKEN }}" # toplevel
        VPN_INTERFACE: wg0
        VPN_SERVICE_PROVIDER: custom # custom because we want to use a specific endpoint
        VPN_TYPE: wireguard
        WIREGUARD_ADDRESSES: "{{ .AIRVPN_WG_IP }}" # prefixed
        WIREGUARD_DNS: "{{ .AIRVPN_DNS }}" # toplevel
        WIREGUARD_ENDPOINT_IP: "{{ .AIRVPN_ENDPOINT_IP }}" # prefixed
        WIREGUARD_ENDPOINT_PORT: "1637"
        WIREGUARD_MTU: "1320"
        WIREGUARD_PRESHARED_KEY: "{{ .AIRVPN_WG_PRESHARED_KEY }}" # prefixed
        WIREGUARD_PRIVATE_KEY: "{{ .AIRVPN_WG_PRIVATE_KEY }}" # prefixed
        WIREGUARD_PUBLIC_KEY: "{{ .AIRVPN_WG_PUBLIC_KEY }}" # toplevel
  dataFrom:
    - extract:
        key: "${VAULT_PREFIX}/airvpn"
    - extract:
        key: airvpn
