---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name romm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        DB_HOST: '{{ index . "host" }}'
        DB_NAME: '{{ index . "dbname" }}'
        DB_PASSWD: '{{ index . "password" }}'
        DB_PORT: '{{ index . "port" }}'
        DB_USER: '{{ index . "user" }}'
        IGDB_CLIENT_ID: "{{ .IGDB_CLIENT_ID }}"
        IGDB_CLIENT_SECRET: "{{ .IGDB_CLIENT_SECRET }}"
        OIDC_CLIENT_ID: "{{ .ROMM_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .ROMM_OIDC_CLIENT_SECRET }}"
        ROMM_AUTH_SECRET_KEY: "{{ .ROMM_AUTH_SECRET_KEY }}"
        STEAMGRIDDB_API_KEY: "{{ .STEAMGRIDDB_API_KEY }}"
  dataFrom:
    - extract:
        key: korg/igdb
    - extract:
        key: korg/romm
    - extract:
        key: korg/steamgriddb
    - extract:
        key: postgres-pguser-romm
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database-secrets
