---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app "${NAMESPACE}-pgo"
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *app
    template:
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .S3_KEY_ID  }}
          repo1-s3-key-secret={{ .S3_SECRET_KEY  }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .POSTGRES_BACKUP_CIPHER_PASS }}
  dataFrom:
    - extract:
        key: "${VAULT_PREFIX}/pgo"
    - extract:
        key: qnap
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pgadmin-oauth2
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        authelia: |-
          {
            "OAUTH2_CLIENT_ID": "{{ .PGADMIN_OIDC_CLIENT_ID }}",
            "OAUTH2_CLIENT_SECRET": "{{ .PGADMIN_OIDC_CLIENT_SECRET }}"
          }
  dataFrom:
    - extract:
        key: "${VAULT_PREFIX}/pgadmin"
