---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ../../../base/security/authelia/helmrelease.yaml
configMapGenerator:
  - name: authelia
    files:
      - configuration.yaml=./resources/configuration.yaml
  - name: letsencrypt-certs
    files:
      - letsencrypt-certs.pem=./resources/letsencrypt-certs.pem
generatorOptions:
  disableNameSuffixHash: true
